### PR TITLE
Added option to display the playlist

### PR DESCRIPTION
**Pull request by DerPipo**
- Added option to show the current playlist if the actionBlock of BeamMusicPlayerViewController is not set.
- Added bar_button@2x.png, playing@2x.png and playlist@2x.png to bundle, to display UI for playlists
  # Modified AutoScrollLabel to enable shortcut-scrolling of the playlist table view (scrollsToTop)
- Added missing connections from xib to BeamMusicPlayerViewController
- Added BeamPlaylistTableViewCell to display details of a song in a UITableView
- Added BeamPlaylistViewController to display the playlist in a UITableView
- Added BeamRadialGradientView to provide a backgroundView for the playlist similar to the music app

### CODE REVIEW

**Comment by HBehrens** [comment]
Thank you for this contribution, Pipo.

Before I look into this in more detail. Could you please assure the build passes  https://travis-ci.org/BeamApp/MusicPlayerViewController/builds/8488100 ? It seems at least one of the unit tests failes due to your changes. If you extract a method to display the playlist VC programmatically (needed if you want to provide such an option in an action block, anyway) you can easily create a partial mock to verify your newly introduced behavior (display playlist on action == nil) in a test.

**Comment by DerPipo** [comment]
I'm new to writing tests, but I fixed the failing one and wrote a new for the playlist visibility. Perhaps it's not exactly what you want, but I tried my best ;-)

**Comment by HBehrens** [comment]
Thanks, Pipo. I've merged your code into the master branch - that's a great addition :)

Are you willing to help me on polishing this further? Instead of making minor adjustments myself over the next days, we could discuss changes via Github issues, first. Do you want me to mention you on those issues to get things rolling?

**Comment by DerPipo** [comment]
Great, let's go ;-)

**Pull request merged**
